### PR TITLE
Use the dedicated example.org domain for demo and no longer mail.com

### PR DESCRIPTION
**Pull request by zero-24**
Hi,

with this PR i just want to make sure that we use the dedicated example.org domain for examples over the mail.com ;)

### CODE REVIEW

**Review by alexandreelise — APPROVED** [review]
Nice catch Tobias. Thanks for the contribution. Take care. Have a nice weekend.

**Comment by zero-24** [comment]
Thanks we are preparing JD Germany live stream event for tomorrow :-D

**Comment by alexandreelise** [comment]
@zero-24 Will the JD Germany be on youtube with english subtitles?

**Comment by zero-24** [comment]
Saddly YouTube is bad with the generation of english subtitles from German.

**Comment by alexandreelise** [comment]
Yes but someone with patience could edit the subtitles file manually...

**Comment by zero-24** [comment]
Sure after the stream is over not for the live event i guess.

**Comment by alexandreelise** [comment]
Sure.

**Pull request merged**
